config/routes.rb
Rails.application.routes.draw do
 root to: "todo_lists#index"

  resources :todo_lists do
    resources :todo_items 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> do
    where(completed: true)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items

  def percent_complete
    return 0 if total_items == 0
    ( 100 * completed_items.to_f / total_items).round()
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items 
      @total_items ||= todo_items.count
  end

  def status
    case percent_complete.to_i
    when 0
      'Not Started'
    when 100
      'complete'
    else 
      'In progress'
    end
  end

  def badge_color
  case percent_complete.to_i
    when 0
      'warning'
    when 100
      'success'
    else 
      'primary'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update_attributes(todo_item_params)
        redirect_to(@todo_item.todo_list)
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy
    redirect_to(@todo_item.todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-3 mh-75">
          <p id="notice"><%= notice %></p>
          <div class="card mt-5 border-0 rounded  border-radius-aniceborder h-80 bg-white">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with(model: [@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :completed_at %><br />
    <%= f.datetime_select :completed_at %>
  </div>
  <div class="field">
    <%= f.label :todo_list %><br />
    <%= f.text_field :todo_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<div class="card-header d-flex justify-content-between align-items-center">
  <h3 class="card-title mt-1">
    Editing todo_item
  </h3>
  <div>
  <%= link_to 'Show', [@todo_item.todo_list, @todo_item], class: 'btn btn-secondary btn-sm'%>
  </div>
</div>
<ul class="list-group">
    <li class="list-group-item bg-light">
      <div class="w-100">
        <%= render 'form' %>
      </div>
    </li>
</ul>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Completed</th>
    <th>Completed at</th>
    <th>Todo list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.description %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.completed_at %></td>
    <td><%= todo_item.todo_list %></td>
    <td><%= link_to 'Show', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
    <td><%= link_to 'Destroy', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_todo_list_todo_item_path(params[:todo_list_id]) %>

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @todo_item.description %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo_item.completed %>
</p>

<p>
  <b>Completed at:</b>
  <%= @todo_item.completed_at %>
</p>

<p>
  <b>Todo list:</b>
  <%= @todo_item.todo_list %>
</p>


<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <div class="input-group mb-4 w-100">
    <%= form.text_field :title, class: 'form-control border-0 aniceborder', placeholder: 'Name your new Todo list here' %>
    <div class="input-group-append">
      <%= form.submit "Add", class: "btn btn-primary input-group-btn" %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="card-header d-flex justify-content-between align-items-center border-0 bg-white aniceborder">
  <h5 class="card-title mt-1">
    Editing a Todo list
  </h5> 
  <div>
  <%= link_to 'Back', @todo_list, class: 'btn btn-secondary btn-sm text-white' %> 
  </div>
</div>
<ul class="list-group border-0 bg-white aniceborder mt-1">
    <li class="list-group-item border-0 bg-white mt-3">
      <div class="w-100">
        <%= render 'form', todo_list: @todo_list %>
      </div>
    </li>
</ul>

app/views/todo_lists/index.html.erb
<div class="card-header d-flex justify-content-between align-items-center border-0 bg-white">
  <h4 class="card-title mt-1">
    Todo List
  </h4>
  <div>
    <%= link_to 'New Todo List', new_todo_list_path, class: 'btn btn-primary btn-sm text-white' %>
  </div>
</div>
<ul class="list-group border-top">
  <% @todo_lists.each do |todo_list| %>
    <li class="list-group-item bg-white border-0">
      <div class="d-flex justify-content-between align-items-center px-2 py-2 mt-2 todoListItem">
        <div class="d-flex justify-content-start gap-2">
          <h5 class="m-0">
            <b><%= link_to todo_list.title, todo_list, class: "text-decoration-none"%></b>
          </h5>
          <p class="m-0">
          <span class="badge badge-pill bg-<%= todo_list.badge_color %>"><%= todo_list.status %></span>
          </p>
        </div>
        <p class="text-secondary m-0"><small><%= todo_list.percent_complete %>% Complete (<%= todo_list.completed_items %> / <%= todo_list.total_items %> Items)</small></p>
      </div>
    </li>
    <% end %>
</ul>

app/views/todo_lists/new.html.erb
<div class="card-header d-flex justify-content-between align-items-center border-0 bg-white aniceborder">
  <h5 class="card-title mt-1">
    Create a new Todo list
  </h5>
  <div>
  <%= link_to 'Back', todo_lists_path, class: 'btn btn-secondary btn-sm text-white' %> 
  </div>
</div>
<ul class="list-group border-0 bg-white aniceborder mt-1">
    <li class="list-group-item bg-light border-0 bg-white ">
      <div class="w-100 mt-2 mb-0">
          <%= render 'form', todo_list: @todo_list %>
      </div>
    </li>
</ul>

app/views/todo_lists/show.html.erb
<div class="card-header d-flex justify-content-between align-items-center border-0 bg-white">
  <div class="d-flex justify-content-center align-items-center gap-4 border-0">
    <div>
      <%= link_to 'Home', todo_lists_path, class: ' text-white btn btn-success btn-sm' %>
    </div>
    <div class="py-2">
      <h5 class="m-0">
        <b><%= @todo_list.title %></b>
        <span class="badge badge-pill bg-<%= @todo_list.badge_color %>"><%= @todo_list.status %></span>
      </h5>
      <p class="text-secondary m-0"><small><%= @todo_list.percent_complete %>% Complete (<%= @todo_list.completed_items %> / <%= @todo_list.completed_items%> Items)</small></p>
    </div>
  </div>
  <div>
    <%= link_to 'Edit', edit_todo_list_path(@todo_list), class: 'btn btn-secondary text-white btn-sm' %>
  </div>
</div>

<div class="card-body border-0 aniceborder-">
  <div class="progress mb-2">
    <div class="progress-bar bg-info" role="progressbar" style="width: <%= @todo_list.percent_complete%>%" aria-valuenow="<%= @todo_list.percent_complete%>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  
  <%= form_for([@todo_list, @todo_item]) do |f| %>
    <div class="input-group mb-4">
      <%= f.text_field :description, class: 'form-control border-0 aniceborder', placeholder: 'Add a todo item' %>
      <div class="input-group-append">
        <%= f.submit "Add", type: 'button', class: "btn btn-primary input-group-btn" %>
      </div>
    </div>
  <% end %>
  
  <ul class="list-group border-0 ">
    <% @todo_list.todo_items.each do |todo_item| %>
      <% if todo_item.completed? %>
        <li class="list-group-item bg-light aniceborder mt-2">
          <div class="d-flex justify-content-between align-items-center">
            <span class="text-secondary">
              <del><%= todo_item.description%></del>
              <span class="badge badge-pill bg-success">Completed</span>
            </span>
            <%= form_with(model: [todo_item.todo_list, todo_item]) do |f| %>
              <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
              <%= button_tag( :class => "btn btn-danger text-white btn-sm") do %>
                <i class="fa fa-square"></i>
              <% end %>
              <%= link_to 'X', [todo_item.todo_list, todo_item], method: :delete, class: "btn btn-dark text-white btn-sm" %>
            <% end %>
          </div>
        </li>
        <% else %>
          <li class="list-group-item border-0 bg-white aniceborder mt-2">
            <div class="d-flex justify-content-between">
              <span class="pt-2">
                <%= todo_item.description%>
              </span>
              <%= form_with(model: [todo_item.todo_list, todo_item]) do |f| %>
                <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
                <%= button_tag( :class => "btn btn-info text-white btn-sm") do %>
                  <i class="fa fa-check"> </i>
                <% end %>
              <%= link_to 'X', [todo_item.todo_list, todo_item], method: :delete, class: "btn btn-dark text-white btn-sm" %>

              <% end %>
            </div>
          </li>
        <% end %>
    <% end %>
  </ul>
</div>